#!/usr/bin/env python3

from __future__ import annotations

import gzip
import hashlib
import re
import subprocess
import sys
from pathlib import Path

GENERATED_SUFFIXES = tuple(
    f".{kind}{suffix}"
    for kind in ("spv", "ptx")
    for suffix in ("", ".gz", ".c", ".o", ".d")
)
SPIRV_MAGIC = bytes.fromhex("03 02 23 07")


def shader_configuration(source: Path) -> bool:
    header = (source / "config.h").read_text()
    match = re.search(
        r"^#define CONFIG_SHADER_COMPRESSION ([01])$", header, re.MULTILINE
    )
    if match is None:
        raise RuntimeError("config.h does not define CONFIG_SHADER_COMPRESSION")
    compressed = match.group(1) == "1"
    makefile = (source / "ffbuild" / "config.mak").read_text()
    make_compressed = bool(
        re.search(r"^CONFIG_SHADER_COMPRESSION=yes$", makefile, re.MULTILINE)
    )
    if compressed != make_compressed:
        raise RuntimeError(
            "config.h and ffbuild/config.mak disagree about shader compression"
        )
    return compressed


def generated_shader_paths(source: Path) -> list[Path]:
    # DUMBAI: Limit cleanup to FFmpeg-owned generated shader files, excluding source and dependency-install trees.
    paths = []
    for library in source.glob("lib*"):
        if library.is_dir():
            paths.extend(
                path
                for path in library.rglob("*")
                if path.is_file() and path.name.endswith(GENERATED_SUFFIXES)
            )
    for path in paths:
        path.resolve().relative_to(source)
    return sorted(paths)


def prepare_shader_payloads(source: Path) -> int:
    source = source.resolve()
    shader_configuration(source)
    paths = generated_shader_paths(source)
    tracked = set(
        subprocess.check_output(["git", "ls-files"], cwd=source, text=True).splitlines()
    )
    for path in paths:
        if path.relative_to(source).as_posix() in tracked:
            raise RuntimeError(f"Refusing to remove tracked shader input: {path}")
    for path in paths:
        path.unlink()
    return len(paths)


def validate_shader_payloads(source: Path) -> dict:
    source = source.resolve()
    compressed = shader_configuration(source)
    payloads = {}
    paths = generated_shader_paths(source)
    for path in paths:
        if not path.name.endswith((".spv.c", ".ptx.c")):
            continue
        text = path.read_text()
        array = re.search(
            r"const unsigned char (\w+)_data\[\]\s*=\s*\{([^}]*)\};", text
        )
        if array is None:
            raise RuntimeError(f"Missing generated byte array: {path}")
        length = re.search(
            rf"const unsigned int {array.group(1)}_len\s*=\s*(\d+);", text
        )
        if length is None:
            raise RuntimeError(f"Missing generated length: {path}")
        data = bytes(
            int(value, 16)
            for value in re.findall(r"0x([0-9a-fA-F]{2})", array.group(2))
        )
        size = int(length.group(1))
        if len(data) != size + 1 or data[-1] != 0:
            raise RuntimeError(f"Generated length/terminator mismatch: {path}")
        data = data[:size]
        is_gzip = data.startswith(bytes.fromhex("1f 8b"))
        if is_gzip != compressed:
            raise RuntimeError(
                f"Shader compression mismatch: {path.relative_to(source)}: "
                f"CONFIG_SHADER_COMPRESSION={int(compressed)}, payload={'gzip' if is_gzip else 'raw'}"
            )
        binary = path.with_suffix("")
        encoded = Path(str(binary) + ".gz") if compressed else binary
        if not encoded.is_file() or encoded.read_bytes() != data:
            raise RuntimeError(f"Generated array does not match shader input: {path}")
        decoded = gzip.decompress(data) if compressed else data
        if binary.name.endswith(".spv"):
            if not decoded.startswith(SPIRV_MAGIC) or len(decoded) % 4:
                raise RuntimeError(f"Invalid SPIR-V header/length: {path}")
        elif not re.search(rb"(?m)^\s*\.version\s+\d+\.\d+", decoded):
            raise RuntimeError(f"Invalid PTX header: {path}")
        payloads[path.relative_to(source).as_posix()] = {
            "bytes": size,
            "sha256": hashlib.sha256(data).hexdigest(),
        }
    if not payloads:
        raise RuntimeError("Vulkan build produced no generated shader payloads")
    if not compressed and any(
        path.name.endswith((".spv.gz", ".ptx.gz")) for path in paths
    ):
        raise RuntimeError(
            "Uncompressed build still contains cached compressed shader payloads"
        )
    return {"compression": compressed, "payloads": payloads}


def main(argv: list[str]) -> int:
    if len(argv) != 2 or argv[0] not in {"prepare", "verify"}:
        print(
            "Usage: validate_shader_payloads.py <prepare|verify> <FFmpeg source>",
            file=sys.stderr,
        )
        return 1
    command, directory = argv
    source = Path(directory)
    try:
        if command == "prepare":
            count = prepare_shader_payloads(source)
            print(f"Removed {count} generated shader cache files before rebuilding")
        else:
            result = validate_shader_payloads(source)
            print(
                f"Verified {len(result['payloads'])} shader payloads; compression={int(result['compression'])}"
            )
    except (OSError, RuntimeError, ValueError, subprocess.CalledProcessError) as error:
        print(f"Shader payload verification failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
